apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-web-server
  template:
    metadata:
      labels:
        app: go-web-server
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: go-web-server
        image: danielhelfand/go-web-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-server-service
  labels:
    app: go-web-server
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: go-web-server
